#ifndef GLITTER_LAYOUT_H
#define GLITTER_LAYOUT_H

//Vertex
#define VERTEX_POSITION_LOC 0
#define VERTEX_NORMAL_LOC 1
#define VERTEX_UV_LOC 2

//Materials
#define MATERIAL_AMBIENT_LOC 0
#define MATERIAL_DIFFUSE_LOC 1
#define MATERIAL_SPECULAR_LOC 2
#define MATERIAL_EMISSION_LOC 3
#define MATERIAL_SHININESS_LOC 4

#define MODEL_VIEW_MATRIX_LOC 10
#define PROJECTION_MATRIX_LOC 11
#define TRANSFORMATION_MATRIX_LOC 12

//Texture
#define DIFFUSE_TEXTURE_SAMPLER 20
#define TEXTURE_ACTIVATE_LOC 21

#endif //GLITTER_LAYOUT_H
